[INFO]: Hi, This is root.
[INFO]: After the configurations are successfully processed and dirs are created.
[INFO]: The pipeline of the project will begin now.
2023/01/04 08:10:40	INFO	wandb	multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023/01/04 08:10:43	INFO	wandb	communicating current version
2023/01/04 08:10:43	INFO	wandb	got version response upgrade_message: "wandb version 0.13.7 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023/01/04 08:10:48	INFO	wandb	atexit reg
2023/01/04 08:10:48	INFO	wandb	redirect: SettingsConsole.WRAP_RAW
2023/01/04 08:10:48	INFO	wandb	Wrapping output streams.
2023/01/04 08:10:48	INFO	wandb	Redirects installed.
2023/01/04 08:10:57	INFO	wandb	Watching
Thread SenderThread:
Traceback (most recent call last):
  File "/esat/smcdata/users/kkontras/Image_Dataset/no_backup/envs/gl_env/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 51, in run
    self._run()
  File "/esat/smcdata/users/kkontras/Image_Dataset/no_backup/envs/gl_env/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/esat/smcdata/users/kkontras/Image_Dataset/no_backup/envs/gl_env/lib/python3.7/site-packages/wandb/sdk/internal/internal.py", line 310, in _process
    self._sm.send(record)
  File "/esat/smcdata/users/kkontras/Image_Dataset/no_backup/envs/gl_env/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 304, in send
    send_handler(record)
  File "/esat/smcdata/users/kkontras/Image_Dataset/no_backup/envs/gl_env/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 1067, in send_output_raw
    output_raw.start()
  File "/esat/smcdata/users/kkontras/Image_Dataset/no_backup/envs/gl_env/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 155, in start
    self._reader_thr.start()
  File "/esat/smcdata/users/kkontras/Image_Dataset/no_backup/envs/gl_env/lib/python3.7/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
wandb: ERROR Internal wandb error: file data was not synced
